employees/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('delete_so_out/<pk>/', views.delete_so_out, name='delete_so_out'),
    path('update_so_out/<pk>', views.update_so_out, name='update_so_out'), 
    path('login_user', views.login_user, name='login'), 
    path('logout/', views.logout_user, name='logout'),
    path('dates', views.date_range_view, name='dates'),
    path('add_transaction', views.add_sout_manually, name='add_transaction'),
    path('view_transaction/<pk>', views.view_transaction, name='view_transaction'),
]

sobran/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('employees.urls')),
]

admin.site.site_header = "Sobran"

employees/models.py
from django.db import models
from datetime import date,datetime,time


class SoEmployee(models.Model):
    em_id_key = models.AutoField(primary_key=True)
    em_name = models.CharField(max_length=50, blank=True, null=True, verbose_name='Employee')
    em_zone = models.IntegerField(blank=True, null=True, verbose_name='Zone')
 
    class Meta:
        managed = True
        db_table = 'so_employees'
        ordering = ['em_name']
    def __str__(self) -> str:
        return self.em_name


class SoOut(models.Model):
    co_id_key = models.AutoField(primary_key=True)
    co_fk_em_id_key = models.ForeignKey('SoEmployee', on_delete=models.CASCADE, null=True, blank=True, verbose_name='Employee')
    co_fk_type_id_key = models.ForeignKey('SoType', on_delete=models.CASCADE, null=True, blank=True, verbose_name='Type',default=1)
    co_date = models.DateField(blank=True, null=True, default=date.today(), verbose_name='Date')
    #co_time_arrived = models.TimeField(auto_now=False, auto_now_add=True)
    co_time_arrived = models.TimeField(auto_now=False, auto_now_add=False, blank=True, null=True, verbose_name='Time Arrived', default=datetime.now().time().strftime('%I:%M'))
    co_time_dif = models.CharField(max_length=45, blank=True, null=True, verbose_name='Time Difference') 
  
    # def save(self, *args, **kwargs):
    #     if self.co_fk_type_id_key_id in [2, 3]:
    #         shift = Shift.objects.first()  # Assuming you have only one Shift instance
    #         red_start = shift.red_start
    #         red_end = shift.red_end
    #         time_diff = datetime.combine(datetime.today(), red_end) - datetime.combine(datetime.today(), red_start)
    #         minutes = int(time_diff.total_seconds() // 60)
    #         if self.co_fk_type_id_key_id == 2:
    #             minutes *= 2
    #         elif self.co_fk_type_id_key_id == 3:
    #             minutes *= 3
    #         hours = minutes // 60
    #         minutes %= 60
    #         self.co_time_dif = f"{hours:02d}:{minutes:02d}"
    #     super().save(*args, **kwargs)
    
    class Meta:
        managed = True
        db_table = 'so_outs'
        verbose_name = 'SO Out' 
        ordering = ['-co_date']

    def __str__(self) -> str:
        return str(self.co_fk_em_id_key)


class SoType(models.Model):
    type_id_key = models.AutoField(primary_key=True)
    description = models.CharField(max_length=45, blank=True, null=True, default="Tardy")

    class Meta:
        managed = True
        db_table = 'so_types'
    def __str__(self) -> str:
        return self.description
    

class Shift(models.Model):
    yellow_start = models.TimeField(blank=True, null=True, verbose_name='Yellow Zone Start', default=time(hour=6, minute=15))
    red_start = models.TimeField(blank=True, null=True, verbose_name='Red Zone Start', default=time(hour=5, minute=00))
    green_start = models.TimeField(blank=True, null=True, verbose_name='Green Zone Start', default=time(hour=4, minute=45))
    
    yellow_end = models.TimeField(blank=True, null=True, verbose_name='Yellow Zone End', default=time(hour=14, minute=45))
    red_end = models.TimeField(blank=True, null=True, verbose_name='Red Zone End', default=time(hour=13, minute=15))
    green_end = models.TimeField(blank=True, null=True, verbose_name='Green Zone End', default=time(hour=12, minute=30))
   
    class Meta:
        managed = True
        db_table = 'shiftstart'

    def save(self, *args, **kwargs):
        # Delete existing Shift object before saving new one
        Shift.objects.exclude(id=self.id).delete()
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return "Zone start time"

employees/forms.py
from django.forms import ModelForm
from django import forms
from .models import SoEmployee, SoOut, SoType, Shift
from django.forms.widgets import DateInput



class SoOutForm(ModelForm):
    class Meta:
        model = SoOut
        fields = ['co_date','co_time_dif','co_time_arrived','co_fk_type_id_key','co_fk_em_id_key']
        labels = { 'co_fk_type_id_key':'Type','co_fk_em_id_key': 'Employee'}
        widgets = {
            'co_fk_em_id_key': forms.Select(attrs={'class':'form-control', 'id':'single1', 'required':'True'}),
            'co_fk_type_id_key': forms.Select(attrs={'class':'form-control', 'id':'single3', 'required':'True'}), 
            'co_time_arrived': forms.HiddenInput(),
            'co_date': forms.HiddenInput(),
            'co_time_dif': forms.HiddenInput()
        }



class UpdateoOutsForm(ModelForm):
    class Meta:
        model = SoOut
        fields = ['co_fk_type_id_key','co_fk_em_id_key','co_date','co_time_dif','co_time_arrived']
        labels = {
            "co_fk_type_id_key": 'Type',
            'co_fk_em_id_key': "Name", 
            'co_date': 'Date',
            'co_time_arrived': 'Time Arrived',
        }

        widgets = { 
            'co_fk_em_id_key': forms.HiddenInput(),
            'co_fk_type_id_key': forms.Select(attrs={'class':'form-control'}), 
            'co_time_arrived': forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'},format='%H:%M'),
            'co_date': DateInput(attrs={'class':'form-control','type': 'date'}),
            'co_time_dif': forms.HiddenInput()
        } 

        
class DateRangeForm(forms.Form):
    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

employees/views.py
from django.shortcuts import render, redirect
from .models import SoEmployee, SoOut, SoType, Shift
from .forms import SoOutForm, UpdateoOutsForm
from datetime import date, datetime, time, timedelta
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from .forms import DateRangeForm 
from django.db.models import Q
from django.http import HttpResponse,HttpResponseBadRequest



def login_user(request):
     
    if request.method == 'POST': 
        username = request.POST.get('username')
        password = request.POST.get('password') 
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home') 
        else:
            messages.info(request, 'Username or password is incorrect')
    return render(request, 'login.html')






def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip_address = x_forwarded_for.split(',')[0]
    else:
        ip_address = request.META.get('REMOTE_ADDR')
    return ip_address

 


@login_required(login_url='login')
def home(request):
    print(get_client_ip(request))
    today = date.today()
    type = SoType.objects.all()
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    end_date_datetime = ""

    if start_date is None or end_date is None or start_date is "" or end_date is "":
        date_range_label = f"Transactions for {datetime.today().date().strftime('%B %d, %Y')}"
        start_date = today
        end_date = today
    else: 
        start_date = request.GET.get('start_date')
        start_date_datetime = datetime.strptime(start_date, '%Y-%m-%d')
        start_date_formatted = start_date_datetime.strftime('%B %d, %Y')  

        end_date = request.GET.get('end_date')
        end_date_datetime = datetime.strptime(end_date, '%Y-%m-%d')
        end_date_formatted = end_date_datetime.strftime('%B %d, %Y')

        date_range_label = f"Transactions for {start_date_formatted} to {end_date_formatted}"
    
    employee_name = request.GET.get('employee_name')
    employee_type = request.GET.get('employee_type')
    check = request.GET.get('check')
    if employee_name is not None and employee_type is not None:
        print(employee_name)
        sout = SoOut.objects.filter(Q(co_date__range=[start_date, end_date]) & Q(co_fk_em_id_key__em_name__exact=employee_name) & Q(co_fk_type_id_key__description__exact=employee_type)) 
        print(f"results with employee name {employee_name} and Type {employee_type} found {sout.count()} results")
        
    elif employee_name is not None and check is None:
        print("check: ", check) 
        #sout = SoOut.objects.filter(Q(co_date__range=[start_date, end_date]))
        sout = SoOut.objects.filter(Q(co_date__range=[start_date, end_date]) & Q(co_fk_em_id_key__em_name__exact=employee_name)) 
        date_range_label = f"Transactions for {employee_name} for {today} | found {sout.count()} results"
        print(f"results with employee name {employee_name} | found {sout.count()} results")
    elif employee_name is not None and check == "on":
        print("check: ", check)
        sout = SoOut.objects.filter(Q(co_fk_em_id_key__em_name__exact=employee_name) & Q(co_date__isnull=False))
        date_range_label = f"All Transactions for {employee_name} | found {sout.count()} results"
        print(f"results with employee name {employee_name}  found {sout.count()} results")
    elif employee_name is None and employee_type is not None and check == "on":
        print("check: ", check)
        sout = SoOut.objects.filter(Q(co_fk_type_id_key__description__exact=employee_type) & Q(co_date__isnull=False))
        date_range_label = f"Transactions for {employee_type} | found {sout.count()} results"
    elif employee_type is not None and employee_name is None:
        sout = SoOut.objects.filter(Q(co_date__range=[start_date, end_date]) & Q(co_fk_type_id_key__description__exact=employee_type))  
        date_range_label = f"Transactions for {employee_type} for {start_date} to {end_date} | found {sout.count()} results" 
    elif employee_type is not None and employee_name is not None:
        sout = SoOut.objects.filter(Q(co_date__range=[start_date, end_date]) & Q(co_fk_em_id_key__em_name__exact=employee_name) & Q(co_fk_type_id_key__description__exact=employee_type)) 
        date_range_label = f"Transactions for {employee_name} and Type {employee_type} found {sout.count()} results || and date ranges specified {start_date} to {end_date} | found {sout.count()} results"
    elif employee_name is not None and employee_type is not None:
        sout = SoOut.objects.filter(co_fk_em_id_key__em_name__exact=employee_name, co_fk_type_id_key__description__exact=employee_type)
        date_range_label = f"Transactions for {employee_name} and Type {employee_type} found {sout.count()} results || and date ranges not specified | found {sout.count()} results"
    elif employee_type is not None and employee_name is None and start_date is None and end_date is None:
        sout = SoOut.objects.filter(co_fk_type_id_key__description__exact=employee_type)
        date_range_label = f"Transactions for Type ({employee_type}) found {sout.count()} results || and date ranges and employee_name not specified either | found {sout.count()} results"
    elif employee_name is not None and check == "on":
        print("check: ", check)
        sout = SoOut.objects.filter(Q(co_fk_em_id_key__em_name__exact=employee_name) & Q(co_date__isnull=True))
        date_range_label = f"Transactions for {employee_name} for {start_date} | found {sout.count()} results"
    elif start_date is today and end_date is today and check == "on":
        sout = SoOut.objects.all()
        date_range_label = f"Showing all Transactions | found {sout.count()} results"
    elif start_date != end_date is not None and employee_name is None and employee_type is None and check is None:
        print("inside start date and end date")
        sout = SoOut.objects.filter(co_date__range=[start_date, end_date])
        date_range_label = f"Transactions for {start_date} to {end_date} | found {sout.count()} results"
    
    #  this doesnt work
    # elif start_date == end_date and employee_name is None and employee_type is None and check is None: 
    #     sout = SoOut.objects.filter(co_date=start_date)
    #     date_range_label = f"Transactions for {start_date} | found {sout.count()} results"
    else:  
        sout = SoOut.objects.filter(co_date=start_date)
        date_range_label = f"Transactions for {start_date} | found {sout.count()} results"
    
    #sout = SoOut.objects.filter(co_date=str(today))
    sout.order_by('-co_date')
    
    time_diff_total = timedelta() 
    emp = SoEmployee.objects.all()
    emp.order_by('-em_name')
    shift = Shift.objects.all() 
     
             

    time_diff_total = timedelta()
    for item in sout:
        if item.co_time_dif is not None and ":" in item.co_time_dif:
            hours, minutes = map(int, item.co_time_dif.split(':'))
            time_diff = timedelta(hours=hours, minutes=minutes)
            time_diff_total += time_diff

    # Calculate the total hours and minutes
    total_minutes = time_diff_total.total_seconds() // 60
    total_hours = total_minutes // 60
    minutes_remaining = total_minutes % 60

    # Format the total time difference as "hh:mm"
    total_time_diff_formatted = f"{int(total_hours):02d}:{int(minutes_remaining):02d}" if time_diff_total else ""
 

    # Convert the total time difference to a formatted string
    total_time_diff_formatted = str(time_diff_total)

    form = SoOutForm(request.POST or None, initial={'co_time_arrived': datetime.now().time(), 'co_date': date.today()})
    if request.method == 'POST':
        employee_name = request.POST.get('co_employee')
        print("employee name: ", employee_name)
        if form.is_valid():
            # Form values
            time_arrived = form.instance.co_time_arrived
            type = form.instance.co_fk_type_id_key.description
            zone = form.instance.co_fk_em_id_key.em_zone

            for x in shift:
                y_start = x.yellow_start
                r_start = x.red_start
                g_start = x.green_start

                y_end = x.yellow_end
                r_end = x.red_end
                g_end = x.green_end

             
            # Get employee name from form and assign it to the instance
            employee_name = request.POST.get('co_employee')
            form.instance.co_fk_em_id_key.em_name = employee_name

            # Check type of absence
            if type == "Vacation" or type == "Call-out":
                if zone == 1: 
                    yellow_shift_start = datetime.combine(datetime.today(), y_start)
                    yellow_shift_end = datetime.combine(datetime.today(), y_end)
                    time_shift = (yellow_shift_end - yellow_shift_start).total_seconds() // 60

                    hours, minutes = divmod(time_shift, 60)
                    formatted_time = '{:02d}:{:02d}'.format(int(hours), int(minutes))

                    # Add 30 minutes to the time
                    time_delta = timedelta(minutes=30)
                    updated_time = datetime.strptime(formatted_time, '%H:%M') - time_delta
                    formatted_updated_time = updated_time.strftime('%H:%M')

                    form.instance.co_time_arrived = None
                    form.instance.co_time_dif = formatted_updated_time

                    form.save()
                    return redirect('home')
                    
                elif zone == 2:
                    print("here from zone 2")
                    red_shift_start = datetime.combine(datetime.today(), r_start)

employees/templates/date.html
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{ form.start_date.id_for_label }}">Start Date:</label>
        {{ form.start_date }}
    </div>
    <div class="form-group">
        <label for="{{ form.end_date.id_for_label }}">End Date:</label>
        {{ form.end_date }}
    </div>
    <button type="submit">Submit</button>
</form>

employees/templates/home.html
{% extends 'base.html' %}

{% block content %}
 
<i class="fa fa-search-plus fa-2x" style="color:#4e73df" data-toggle="modal" data-target="#advancedSearchModal" id="hidden-search-form-icon" aria-hidden="true"> Search</i>
 <br>
 
<div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">{{date_range_label}}</h6>
                                </div>
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <table class="table table-bordered table-striped" id="dataTable2" width="100%" cellspacing="0">
                                            <thead>
                                                <tr>
                                                    <th>Name</th>
                                                    <th>Type</th>
                                                    <th>Date</th>
                                                    <th>Time Arrived / Left</th>
                                                    <th>Abs (total: {{ total_time_diff }})</th>
                                                    <th>edit</th>
                                                    <th>delete</th>
                                                </tr>
                                            </thead>
                                            <tfoot>
                                                <tr>
                                                   <th>Name</th>
                                                    <th>Type</th>
                                                    <th>Date</th>
                                                    <th>Time Arrived</th>
                                                    <th>Abs (total: {{ total_time_diff }})</th>
                                                    <th>edit</th>
                                                    <th>delete</th>
                                                </tr>
                                                
                                            </tfoot>
                                            <tbody>

                                            {% for x in sout %}
                                            <tr>
                                                <td><a href="{% url 'view_transaction' x.co_id_key %}" >{{x.co_fk_em_id_key.em_name}}</a> </td>
                                                <td>{{x.co_fk_type_id_key}}</td>
                                                <td>{{x.co_date}}</td>  
                                                {% if x.co_time_arrived == None %}
                                                <td></td>
                                                <td>{{x.co_time_dif}}</td>
                                                {% else %}
                                                <td>{{x.co_time_arrived}}</td> 
                                                <td>{{x.co_time_dif}}</td>
                                                {% endif %} 
                                                                              
                                                <td><a href="{% url 'update_so_out' x.co_id_key %}" ><i class="fa fa-pen-alt"></i></a></td>
                                                
                                                  <td>
                                                     <form id="delete-form-{{ x.co_id_key }}" method="POST" action="{% url 'delete_so_out' x.co_id_key %}">
                                                        {% csrf_token %}
                                                        <input type="hidden" name="co_id" value="{{ x.co_id_key }}">
                                                        <a type="submit" class="delete-btn" style="color:red"><i class="fa fa-trash"></i></a>
                                                    </form>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>

                                <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                                <script>
                                $(document).ready(function() {
                                $('.delete-btn').click(function(event) {
                                    event.preventDefault(); // Prevent default form submission

                                    var form = $(this).closest('form'); // Get the parent form
                                    var formId = form.attr('id'); // Get the form ID

                                    $.ajax({
                                    type: 'POST',
                                    url: form.attr('action'),
                                    data: form.serialize(), // Serialize form data
                                    success: function(response) {
                                        // Handle successful response
                                        // For example, you can remove the deleted row from the table
                                        $('#' + formId).closest('tr').remove();
                                    },
                                    error: function(xhr, errmsg, err) {
                                        // Handle error response
                                        console.log(xhr.status + ": " + xhr.responseText);
                                    }
                                    });
                                });
                                });
                                </script>


                                                        <!-- transaction Modal  data-toggle="modal" data-target="#addTransactionModal"-->
                            <div class="modal fade" id="addTransactionModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Add Transaction</h5>
                                                     
                                        </div>
                                         <div class="container">
                                           {% include 'add_transaction_form.html' %}
                                         </div> 
                                         <br><br> 
                                    </div>
                                </div>
                            </div>
                                            
                            
                            
                            
                            <!-- advancedSearchModal Modal  data-toggle="modal" data-target="#advancedSearchModal"-->
                            <div class="modal fade" id="advancedSearchModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title m-auto" id="exampleModalLabel">Search Reports</h5>
                                                     
                                        </div>
                                         <div class="container">
                                                                       <!-- hidden div-->
                                            <form action="" id="date_range_form_home" class="p-3">
                                            <div class="form-group">
                                            <label for="start2" >Start Date</label>
                                            <input type="date" id="start2" value="{{date_today}}" name="start_date" class="form-control" />
                                            </div>
                                            <div class="form-group">
                                            <label for="end2" >End Date</label>
                                            <input type="date" id="end2" name="end_date" id="end_input" class="form-control" />
                                            </div>
                                            <div class="form-group">
                                            <label for="name" >Employee</label>
                                                <select name="employee_name" id="employee_name" class="form-control">
                                                    <option value="" disabled selected>Select Employee</option>
                                                    {% for x in emp %}
                                                    <option value="{{x.em_name}}">{{x.em_name}}</option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label for="name">Name</label>
                                                <select name="employee_type" id="employee_type" class="form-control">
                                                <option value="" disabled selected>Select Type</option>
                                                {% for x in type %}
                                                <option value="{{x}}">{{x}}</option>
                                                {% endfor %}
                                                </select>
                                            </div>
                                               <div class="input-group-text" style="background:#fff; border:0; color:#000">
                                                    <input type="checkbox" name="check" aria-label="Checkbox for following text input">
                                                    Show All
                                               </div>
                                            <button type="submit" class="btn btn-primary" id="sidebar_submit" name="sidebar_submit">Search</button>
                                            <a href="{% url 'home' %}" type="submit" class="btn btn-primary">Reset</a>
                                           
                                        </form>


                                         </div>  
                                    </div>
                                </div>
                            </div>
                         
                         
                         
                         
                            <!-- infoModal Modal  data-toggle="modal" data-target="#infoModal"-->
                            <div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title m-auto" id="exampleModalLabel">information</h5>
                                                     
                                        </div>
                                         <div class="container">
                                         
                                            <table>
                                            <tr><td>Name</td>
                                                <td>Type</td>
                                                <td>Zone</td>
                                                
                                            </tr>
                                            <tr>
                                            <td>{{name}}</td>
                                            <td>{{so_type}}</td>
                                            <td>{{zone}}</td>
                                            </tr>
                                            </table>

                                         </div>  
                                    </div>
                                </div>
                            </div>




   <!--  auto set dates form start to end form  -->                        
 
{% endblock content %}

employees/templates/transaction.html
{% extends 'base.html' %} {% block content %}

<div class="card" style="width: 18rem">
  <div class="card-body">
    <h5 class="card-title mb-3">{{sout.co_date}}</h5>

    <p class="card-text">Name: {{sout.co_fk_type_id_key}}</p>
    <p class="card-text">Arrived: {{sout.co_time_arrived}}</p>
    <p class="card-text">Zone: {{sout.co_fk_em_id_key.em_zone}}</p>
    <p class="card-text">Tardy: {{sout.co_time_dif}}</p> 
    <a href="#" class="btn btn-primary" onclick="history.back()">Go back</a>
  </div>
</div>
{% endblock %}

employees/templates/update_co.html
{% extends 'base.html' %}

{% block content %}

<form method="post">

    {% csrf_token %}
    <label style="font-size: larger;">Employee Name: <b>{{name}}</b></label>
    <div class="mb-3" style="max-width: 300px;">
        {{form2.as_table}} 
        
        <br>
   
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    {% comment %} $(document).ready(function () {
            $('#id_co_fk_type_id_key').on('change', function () {
                var optionSelected = $(this).find("option:selected");
                var valueSelected = optionSelected.val();

                if (valueSelected == 2 || valueSelected == 3) {
                    console.log("vacation selected");
                    $('#time').val('');
                }
            });
        });

</script> {% endcomment %}

<!-- <select name="type" id="type" class="form-control"> 
    {% for x in so_type %}
    <option value="{{x}}">{{x}}</option>
    {% endfor %}
</select> -->

{% endblock %}